### ISSUE TITLE
How to change the calendar ui

### ISSUE THREAD

**Issue by venubollu** [misha130/datepicker-ionic2#11]
I want to change the calendar ui look like as @dovk changed in issue #6 ....

can you tell me how to change that one...

**Comment by dovk** [comment]
This is not in any way part of or instead of the excellent work Misha has done - for my own purposes I took the html code out of **_datepicker.component.ts_** template and made a separate file **_datepicker.html_** (attached here as **_.txt_**) which I reference from **_datepicker.component.ts_** as `templateUrl: 'datepicker.html'` . That's it as far as the UI is concerned. 
There were another few small changes I made such as in **_datepicker.component.ts_** I uncommented the following 3 lines because the 1st of the month was starting in the first column of the first row on not on the actual day of the week it was supposed to have been - 
```
firstDay = dateList[0].getDay();
// for (var j = 0; j < firstDay; j++) {
//     dateList.unshift(undefined);
// }
```
I also took out the OK/Cancel buttons and had it return "OK" when clicking on any relevant day or button, and "dismiss" itself whenever clicked anywhere other than relevant input.
In any case, I am grateful to Misha for doing such a great job!
I hope this helps
[datepicker.txt](https://github.com/misha130/datepicker-ionic2/files/800111/datepicker.txt)

**Comment by venubollu** [comment]
I done all changes you told above but my UI is not changed and getting errors
![capture](https://cloud.githubusercontent.com/assets/22388956/23328847/4a5d20f6-fae0-11e6-8db9-7e49b52d253c.PNG)
![capture1](https://cloud.githubusercontent.com/assets/22388956/23328849/579d971e-fae0-11e6-9509-798d3be4e73a.PNG)

**Comment by dovk** [comment]
It looks like something else might be missing, I just sent what worked for me regarding the UI. I'm sure you'll work it out, it did for me. The only thing you need to change is the html, so you don't have to take what I sent, just alter the template in a similiar way or on the way that you'd like, no need to change anything else from Misha's original.

**Comment by venubollu** [comment]
No @dovk i am not changing Misha's original code chat remove the html code and do as you told above..
